// Regression flags for the Forge visual-verifier fixture.
//
// Each flag toggles a deliberate visual bug the verifier must catch.
// `off` is the master kill-switch used for golden-path screenshots:
// when `off` is true, no regression applies regardless of the other flags.
//
// This file is intentionally simple — the fixture's value comes from the
// bugs being easy to spot (both by a Playwright verifier and by a human
// reviewing evidence screenshots), not from a fancy toggle system.
//
// T023 / spec-mock-and-visual-verify R003: the E2E executor run landed
// the surgical fix by flipping each flag to false. Flags remain in the
// file so the fixture can be reverted to its broken state by setting any
// (or all) of halo/zoomOut/synthesis back to true — that is how the
// before/after audit evidence (R004) is regenerated by demo.sh.
export const regressions = {
  halo: false,
  zoomOut: false,
  synthesis: false,
  off: false
};
